### ISSUE TITLE
⚙️ [Setting] 프로젝트 파일 초기 세팅

### ISSUE THREAD

**Issue by wjdalswl** [SSU-RETURN/emuda-front#1]
## 📝 개요
- 프로젝트 파일 초기 세팅

## ✔️ To-Do
- [x] React 파일 생성
- [x] gitignore 파일 생성
- [x] 이슈 템플릿 설정
- [x] 이슈 라벨 수정
- [x] pr 템플릿 설정

## 👀 ETC
- https://dobi852.tistory.com/36
