### ISSUE TITLE
✨ [Feat] Recommendation View 제작

### ISSUE THREAD

**Issue by bobo9245** [SSU-RETURN/emuda-front#12]
## 📝 개요
- Recommendation View 제작

## ✔️ To-Do
- [x] Recommendation View 제작(일기 안썼을때)
- [x] Recommendation View 제작(일기 썼을때)
- [x] 더보기 View 제작
