### ISSUE TITLE
✨ [Feat] SearchMusicView UI 작업하기

### ISSUE THREAD

**Issue by wjdalswl** [SSU-RETURN/emuda-front#19]
## 📝 개요
-  SearchMusicView UI 작업하기

## ✔️ To-Do
- [x] 최근 검색어 구현
- [x] 최근 검색어 없을 시 구현
- [x] 검색 후 화면 구현
