### ISSUE TITLE
✨ [Feat] MusicCard UI 작업하기

### ISSUE THREAD

**Issue by wjdalswl** [SSU-RETURN/emuda-front#21]
## 📝 개요
- MusicCard UI 작업하기

## ✔️ To-Do
- [x] MusicCard UI 앞면 작업하기
- [x] MusicCard UI 뒷면 작업하기
- [x] MusicCard 애니메이션으로 카드 뒤집히는 효과 넣기
