### ISSUE TITLE
✨ [Feat] DetailDiaryView UI 작업하기

### ISSUE THREAD

**Issue by wjdalswl** [SSU-RETURN/emuda-front#24]
## 📝 개요
- DetailDiaryView UI 작업하기

## ✔️ To-Do
- [x] DetailDiaryView UI 작업하기
- [x] 이미지 있는 ver
- [x] 이미지 없는 ver
