### ISSUE TITLE
✨ [Feat] PlaylistView, Graph Component 작업#28

### ISSUE THREAD

**Issue by bobo9245** [SSU-RETURN/emuda-front#28]
## 📝 개요
- PlaylistView 수정, Graph Component 작성

## ✔️ To-Do
- [x] PlaylistView 렌더링 조절
- [x] PlaylistView 스크롤 구현
- [x] Graph 컴포넌트 만들기
- [x] PlayListCell 컴포넌트 조금 수정 -> min-height를 지정해서 많은 컴포넌트를 load했을 때 뭉개지는 현상 방지

## 👀 ETC
- 참고자료 등 기타 내용 작성

**Comment by bobo9245** [comment]
## ✔️ To-Do
- [x] PlaylistView 렌더링 조절 -> 안해도 될 것 같다고 생각해서 일단 진행 따로 안했습니다.
- [x] PlaylistView 스크롤 구현
- [x] Graph 컴포넌트 만들기
- [x] PlayListCell 컴포넌트 조금 수정 -> min-height를 지정해서 많은 컴포넌트를 load했을 때 뭉개지는 현상 방지
