### ISSUE TITLE
✨ [Feat] PreferenceView 작업

### ISSUE THREAD

**Issue by JuHyeonAh** [SSU-RETURN/emuda-front#33]
## 📝 개요
- 사용자의 노래 취향을 입력받는 페이지를 제작할 예정

## ✔️ To-Do
- [x] 취향 입력 시작 뷰
- [x] 선호 장르 뷰
- [x] 감정별 노래 취향 뷰
- [ ] 최종 노래 취향 뷰
