### ISSUE TITLE
✨ [Feat] 일기 관련 화면 간 이동 (navigation) 연결

### ISSUE THREAD

**Issue by wjdalswl** [SSU-RETURN/emuda-front#38]
## 📝 개요
- 화면 간 이동 (navigation) 연결

## ✔️ To-Do
- [x] 일기 상세 화면에서 edit button -> 일기 수정 화면 넘기기
- [x] 일기 상세 화면에서 delete button -> 홈 화면 넘기기
- [x] 일기 작성 화면에서 음악찾기 button -> SearchMusicView 넘기기
- [x] 일기 작성 화면에서 다음 button -> MusicCardView 넘기기
- [x] MusicCardView에서 다음 button -> 일기 상세 화면 넘기기
- [x] 일기 수정 화면 완료 button -> 일기 상세 화면 넘기기

## 👀 ETC
일기 감정 그래프 화면 생기면 중간에 아래 부분으로 수정필요
- [ ] 일기 작성 화면에서 다음 button -> 일기 감정 그래프 화면 넘기기
- [ ] 일기 감정 그래프에서 다음 button -> MusicCardView화면 넘기기
- [ ] MusicCardView에서 다음 button -> 일기 상세 화면 넘기기
