### ISSUE TITLE
✨ [Feat] 음악 관련 API 연결

### ISSUE THREAD

**Issue by bobo9245** [SSU-RETURN/emuda-front#41]
## 📝 개요
- 플레이리스트 관련 API 연결

## ✔️ To-Do
- [x] 일기생성시 음악저장 
- [x] 일기생성시 음악검색
- [x] 날짜별 음악 조회
- [x] 감정별 음악 조회
- [ ] AI 플레이리스트 일기조회
- [ ] 감정값 반환 API 적용

## 👀 ETC
- 참고자료 등 기타 내용 작성
