### ISSUE TITLE
✨ [Feat] 플레이리스트 cell 컴포넌트 제작

### ISSUE THREAD

**Issue by wjdalswl** [SSU-RETURN/emuda-front#5]
## 📝 개요
- 플레이리스트 cell 컴포넌트 제작

## ✔️ To-Do
- [x] 플레이리스트 cell 체크박스 var 제작
- [x] 플레이리스트 cell xMark var 제작
- [x] 플레이리스트 cell 최근날짜 var 제작
- [x] 플레이리스트 cell 한줄 소개 var 제작
