### ISSUE TITLE
✨ [Feat] 로그인 분기 처리

### ISSUE THREAD

**Issue by wjdalswl** [SSU-RETURN/emuda-front#76]
## 📝 개요
- 로그인 분기 처리

## ✔️ To-Do
- [ ] 로그인 시 취향 존재하면 바로 메인 화면으로 이동
- [ ] 로그인 시 취향 존재하지 않으면 취향 설정 1페이지로 이동
- [ ] 로그인 안했을때 나머지 페이지 이동 방지
- [ ] 자동 로그인
