### ISSUE TITLE
🔧 [Fix] 메인화면 취향 플레이리스트 생성, 일기 생성 수정

### ISSUE THREAD

**Issue by JuHyeonAh** [SSU-RETURN/emuda-front#87]
## 📝 개요
- 취향 입력 시 취향 플리를 생성하지 않아 최초 회원가입하고 들어왔을 때 취향 플레이리스트가 작동하지 않음
- 일기 생성 화면에서 음악 검색을 하고 돌아왔을 때 감정 입력 되어있어도 또 눌러야 비활성화
- 일기 생성 화면에서 음악 검색 후 돌아왔을 때 이미지 전송 안됨

## ✔️ To-Do
- [x] 취향 플리 생성 해결
- [x] 일기 버튼 비활성화 해결
- [x] 이미지 전송 해결
